### ISSUE TITLE
Spatial bias in dataset

### ISSUE THREAD

**Issue by calebrob6** [zhu-xlab/SSL4EO-S12#3]
Hey, I just wanted to flag that the patches in this dataset have a strongly biased spatial distribution (more so than you might expect from sampling around the 10k most populated points 🙂) due to the sampling strategy. Places that have few Sentinel scenes with <10% cloud cover will be sampled much less frequently (this leads to places like Ireland and India to have very few samples), and places that happen to have more Sentinel scenes in general will be sampled more frequently (this is why you observe striping artifacts in the distribution).

The below figures show a heatmap of the centroid points in the dataset with 5km x 5km cells (where counts are summarized in a 20km window) using the "Heatmap (KDE)" tool in QGIS. The legend ranges from black (1 sample) to yellow (35 samples). You can see that Kolkata, India has 0 samples despite being highly populated -- I'm guessing because of the monsoons that there is always cloud cover during part of the year.

**NOTE**: the same problems are present in the SECO datasets (to a greater extent because that dataset doesn't include the no-overlap constraint).

![image](https://user-images.githubusercontent.com/1088078/220215940-3d1a9f68-c701-45d9-ad48-ac4bfbd3c337.png)

![image](https://user-images.githubusercontent.com/1088078/220216187-63db55c9-925a-4310-818c-26e7e51a12b4.png)

![image](https://user-images.githubusercontent.com/1088078/220216250-8cdcfbf8-d361-4ec2-a104-97b8e0c73709.png)

**Comment by wangyi111** [comment]
Hi @calebrob6 , thanks for the valuable feedback! 

Yes, we also realized the issue of sampling bias due to constraints like cloud coverage (impressive illustration you did!), especially when there should be a "cloud-free" patch for "each season". In the current dataset, we hope it wouldn't bias much the pre-training in practice, as long as the land cover of those few-sample regions does not differ much from the others. This might not be true though:)

We've thought about ways to improve the distribution, e.g. add samples from more years, or allow for a bit higher cloud coverage for such regions. Actually, this might be a valuable comparison also to check the above assumption (or hope). It would also be interesting to see if the current pre-trained weights transfer well on those few-sample regions. Certainly all these as well as other feedback will help us provide a nice update:)

**Comment by calebrob6** [comment]
Yep, makes sense! I don't think this is a problem per se; just wanted to point it out in case others weren't aware!


> It would also be interesting to see if the current pre-trained weights transfer well on those few-sample regions.

I agree! You already show that you definitely get improved spatial generalization on So2Sat, but does that hold everywhere? Maybe this can be tested in an unsupervised way using the existing pre-trained models and new imagery sampled from the sparsely sampled regions. I'll think about it more.

> PS: very much appreciate your deep analysis again. I like the figures!

Thanks! I appreciate your paper -- great work 🙂!
